#!/bin/bash
set -e

if [ ! -f "/ssl_certs/cert.crt" ] || [ ! -f "/ssl_certs/cert.key" ]; then
	openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -subj '/CN=simplesamlphp' -out /ssl_certs/cert.crt -keyout /ssl_certs/cert.key
fi

/var/install-simplesamlphp.sh

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
